name: dataflo-ci

on:
  push:
    branches: [release-1.15.0-rc1-fentik, release-1.15.0-fentik]
  pull_request:
    branches: [release-1.15.0-rc1-fentik, release-1.15.0-fentik]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    strategy:
      max-parallel: 4
      matrix:
        java-version: '11'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          #cache: 'maven'
      - run: mvn install -DskipTests -Dfast

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          channel: '#ziga-test'
        if: always()

