name: flink-ci

on:
  push:
    branches: [release-1.16.1-fentik]
  pull_request:
    branches: [release-1.16.1-fentik]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    strategy:
      max-parallel: 4

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
          server-id: rubicon_github
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      -  uses: s4u/maven-settings-action@v2.8.0
         with:
           githubServer: false
           servers: '[{"id": "rubicon_github", "username": "sergeitsar", "password": "${{ secrets.PRESTO_MAVEN_REPO }}"}]'
           mirrors: '[{"id": "repository.jboss.org-unblocker", "name": "jboss", "mirrorOf": "repository.jboss.org", "url": "http://repository.jboss.org/nexus/content/groups/public/"}, {"id": "conjars-unblocker", "name": "conjars", "mirrorOf": "apache.snapshots", "url": "http://repository.apache.org/snapshots"}]'
      - run: |
          ./fentik-build.sh --package
          pushd fentik-docker
          ./build-docker.sh
          popd
        env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_EC2_METADATA_DISABLED: true
           MAVEN_USERNAME: sergeitsar
           MAVEN_PASSWORD: ${{ secrets.PRESTO_MAVEN_REPO }}

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          channel: '#fentik-github'
        if: always()

